name: Daily Watsons Scrape and Update

on:
  schedule:
    - cron: '0 20 * * *'  # Runs at 20:00 UTC, which is 4:00 AM UTC+8
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager beautifulsoup4 requests

      - name: Run the scraping script
        run: python get_watsons_product_links.py -o watsons_products.json

      - name: Create beauty4 directory
        run: mkdir -p beauty4

      - name: Move JSON file to beauty4 directory
        run: mv watsons_products.json beauty4/

      - name: Configure Git
        run: |
          git config --local user.email "amyhsiao@gmail.com" # Replace with your GitHub email
          git config --local user.name "amyhsiao" # Replace with your GitHub username

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Daily scrape: Update beauty4/watsons_products.json"
          file_pattern: beauty4/watsons_products.json
