name: Daily Product Scrape and Update
on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:
    inputs:
      run_watsons:
        description: 'Run Watsons scraper'
        required: false
        type: boolean
        default: false
      run_poya:
        description: 'Run Poya scraper'
        required: false
        type: boolean
        default: false
      run_cosmed:
        description: 'Run Cosmed scraper'
        required: false
        type: boolean
        default: false
      run_all:
        description: 'Run all scrapers'
        required: false
        type: boolean
        default: true

jobs:
  scrape_watsons:
    if: ${{ github.event_name == 'schedule' || github.event.inputs.run_watsons == 'true' || github.event.inputs.run_all == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      watsons_success: ${{ steps.scrape.outcome == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager beautifulsoup4 requests tqdm
      - name: Run Watsons scraper
        id: scrape
        run: python scrape_watsons.py
        continue-on-error: true
      - name: Configure Git
        if: ${{ steps.scrape.outcome == 'success' }}
        run: |
          git config --local user.email "amyhsiao@gmail.com"
          git config --local user.name "amyhsiao"
      - name: Commit Watsons changes
        if: ${{ steps.scrape.outcome == 'success' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Daily scrape: Update Watsons product data"
          file_pattern: beauty4/watsons_*.json
          push: false

  scrape_poya:
    if: ${{ github.event_name == 'schedule' || github.event.inputs.run_poya == 'true' || github.event.inputs.run_all == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      poya_success: ${{ steps.scrape.outcome == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager beautifulsoup4 requests tqdm
      - name: Run Poya scraper
        id: scrape
        run: python scrape_poya.py
        continue-on-error: true
      - name: Configure Git
        if: ${{ steps.scrape.outcome == 'success' }}
        run: |
          git config --local user.email "amyhsiao@gmail.com"
          git config --local user.name "amyhsiao"
      - name: Commit Poya changes
        if: ${{ steps.scrape.outcome == 'success' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Daily scrape: Update Poya product data"
          file_pattern: beauty4/poya_*.json
          push: false

  scrape_cosmed:
    if: ${{ github.event_name == 'schedule' || github.event.inputs.run_cosmed == 'true' || github.event.inputs.run_all == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      cosmed_success: ${{ steps.scrape.outcome == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager beautifulsoup4 requests tqdm
      - name: Run Cosmed scraper
        id: scrape
        run: python scrape_cosmed.py
        continue-on-error: true
      - name: Configure Git
        if: ${{ steps.scrape.outcome == 'success' }}
        run: |
          git config --local user.email "amyhsiao@gmail.com"
          git config --local user.name "amyhsiao"
      - name: Commit Cosmed changes
        if: ${{ steps.scrape.outcome == 'success' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Daily scrape: Update Cosmed product data"
          file_pattern: beauty4/cosmed_*.json
          push: false

  update_info:
    needs: [scrape_watsons, scrape_poya, scrape_cosmed]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Update scrape info and commit
        run: |
          python update_scrape_info.py ${{ needs.scrape_watsons.outputs.watsons_success }} ${{ needs.scrape_poya.outputs.poya_success }} ${{ needs.scrape_cosmed.outputs.cosmed_success }}
          git config --local user.email "amyhsiao@gmail.com"
          git config --local user.name "amyhsiao"
          git add beauty4/scrape_info.json
          git commit -m "Daily scrape: Update info" || echo "No info changes to commit"
        shell: python

  push_changes:
    needs: update_info
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Pull latest changes
        run: git pull origin master --rebase
      - name: Push all changes
        run: git push origin master
